import java.util.ArrayList;

public class GenerateJuliaPoints {
	
	/**
	 * 
	 * This class generates Julia set points and stores them in an arraylist
	 * 
	 * numbers checked are within the set we expect the MandelBrot set :
	 * 
	 *  xMin = -2, xMax = 2
	 *  yMin = -2, yMx = 2
	 *  
	 *  points generated by the for loops are chjecked whether they are in the MandelBrot set by the method
	 *  isMandelBrot() returns a boolean, if true = added to the ArrayList sets
	 * 
	 * */
	
	private ArrayList<Double>sets = new ArrayList<>();
	private int ESCAPE_THRESHOLD = 2;
	private JuliaSets julias = new JuliaSets();
	private BoundaryChecker mandels = new BoundaryChecker();
	
	
	//create arrayList of JuliaSets
	
	public ArrayList<Double> generateJuliaPoints(){
		
		
		for (double i = -2.0; i<ESCAPE_THRESHOLD; i += 0.2718) {
			
			for(double j = -2.0; j<ESCAPE_THRESHOLD; j += 0.2718) {
				
				if(mandels.isMandelBrot(i, j)) {
					sets.add(i);
					sets.add(j);
				}
			}
			
			
		}
		return sets;
		
	}
	
	//getter for the JuliaPoints list
	
	public ArrayList<Double> getPointsList(){
		return sets;
	}
	

	
}
